=pod

=encoding utf8

=head1 名称

hjj_tiezi_rank.pl 红晋江贴子评分

=head1 说明

需求来自 bubble7733 ，同人文库不同CP贴子太多看不过来

做一个查询贴子并自动评分的工具

当前评分算法：

评分小数部分（来自bubble7733）：整楼回复中水贴比例（贴子热度）

评分整数部分：长贴点击质量（平均点击热度，惩罚短楼层），用等差数列补偿后续楼层


=head2 示例

    查 HJJ 同人文库中，主题出现“宗祥”的贴子评分，楼层字数<800认为是水贴，页数点击量补偿因子设为0.1

    perl hjj_tiezi_rank.pl -B 36 -q 贴子主题 -k 宗祥 -n 800 -d 0.1 -o sample.html

=head1 参数 

    -B 版块序号，例如同人文库为36
    -q 查询类型
    -k 查询关键字
    -n 楼层水贴字数阈值
    -d 页数点击量补偿因子
    -o 输出的html文件名

=head1 安装

需要perl环境 

    cpan App::cpanminus
    cpanm Template
    cpanm Novel::Robot

=cut
